version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    open-pull-requests-limit: 10
    groups:
      gomod:
        update-types:
          - "patch"
