version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-checks:
        - appendCombine
        - badLock
        - badRegexp
        - badSorting
        - boolExprSimplify
        - builtinShadow
        - builtinShadowDecl
        - commentedOutCode
        - commentedOutImport
        - deferInLoop
        - deferUnlambda
        - docStub
        - dupImport
        - dynamicFmtString
        - emptyDecl
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - evalOrder
        - exposedSyncMutex
        - externalErrorReassign
        - filepathJoin
        - hexLiteral
        - httpNoBody
        - hugeParam
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - preferDecodeRune
        - preferFilepathJoin
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - redundantSprint
        - regexpPattern
        - regexpSimplify
        - returnAfterHttpError
        - ruleguard
        - sliceClear
        - sloppyReassign
        - sortSlice
        - sprintfQuotedString
        - sqlQuery
        - stringConcatSimplify
        - stringXbytes
        - stringsCompare
        - syncMapLoadAndDelete
        - timeExprSimplify
        - tooManyResultsChecker
        - truncateCmp
        - typeAssertChain
        - typeDefFirst
        - typeUnparen
        - uncheckedInlineErr
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - yodaStyleExpr
        - badSyncOnceFunc
        - todoCommentWithoutDetail
    gocyclo:
      min-complexity: 40
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocritic
          - golint
        path: fake_.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
